codecov:
  require_ci_to_pass: false

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
