codecov:
  require_ci_to_pass: false

comment:
  layout: 'header, diff, flags, files'

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
